color(black).
color(white).
color(red).
color(blue).
northtexas(Wise,Denton,Parker,Tarrant,Collin,Dallas,Hunt,Rockwall,Kaufman,Van_Zandt,Hood,Johnson,Ellis,Navarro):-
    adjacent(Wise, Denton),
adjacent(Wise, Parker),
adjacent(Wise, Tarrant),
adjacent(Denton, Collin),
adjacent(Denton, Rarrant),
adjacent(Denton, Dallas),
adjacent(Collin, Hunt),
adjacent(Collin, Dallas),
adjacent(Collin, Rockwall),
adjacent(Hunt, Rockwall),
adjacent(Hunt, Kaufman),
adjacent(Hunt, Van_Zandt),
adjacent(Parker, Tarrant),
adjacent(Parker, Hood),
adjacent(Parker, Johnson),
adjacent(Tarrant, Dallas),
adjacent(Tarrant, Johnson),
adjacent(Tarrant, Ellis),
adjacent(Dallas, Rockwall),
adjacent(Dallas, Kaufman),
adjacent(Dallas, Ellis),
adjacent(Rockwall, Kaufman),
adjacent(Rockwall, Van_Zandt),
adjacent(Kaufman, Van_Zandt),
adjacent(Kaufman, Ellis),
adjacent(Hood, Johnson),
adjacent(Johnson, Ellis),
adjacent(Ellis, Navarro),
adjacent(Denton, Wise),
adjacent(Parker, Wise),
adjacent(Tarrant, Wise),
adjacent(Collin, Denton),
adjacent(Tarrant, Denton),
adjacent(Dallas, Tarrant),
adjacent(Hunt, Collin),
adjacent(Dallas, Collin),
adjacent(Rockwall, Collin),
adjacent(Rockwall, Hunt),
adjacent(Kaufman, Hunt),
adjacent(Van_Zandt, Hunt),
adjacent(Tarrant, Parker),
adjacent(Hood, Parker),
adjacent(Johnson, Parker),
adjacent(Dallas, Tarrant),
adjacent(Johnson, Tarrant),
adjacent(Ellis, Tarrant),
adjacent(Rockwall, Dallas),
adjacent(Kaufman, Dallas),
adjacent(Ellis, Dallas),
adjacent(Kaufman, Rockwall),
adjacent(Van_Zandt, Rockwall),
adjacent(Van_Zandt, Kaufman),
adjacent(Ellis, Kaufman),
adjacent(Johnson, Hood),
adjacent(Ellis, Johnson),
adjacent(Navarro, Ellis).

adjacent(Color1,Color2):-color(Color1),color(Color2), Color1 \= Color2.